language: node_js
version: 1.0
node_js:
  - "node"
install:
  - npm ci
stages:
  - name: test
    if: branch = master
  - name: deploy-gh
    if: tag =~ ^v[0-9].+
  - name: release-npm
    if: tag =~ ^v[0-9].+
jobs:
    include:
      - stage: test
        name: "Test and upload coverage to Coveralls"
        script: "npm run test:coverage:coveralls"
      - stage: deploy-gh
        name: "Deploy to Github Pages"
        script: NODE_ENV=production npm run doc -- "$TRAVIS_TAG"
        deploy:
          local_dir: docs/public
          target_branch: staging
          repo: justjs/justjs.github.io
          provider: pages
          github_token: $GITHUB_TOKEN
          skip_cleanup: true
          keep_history: true
          on:
            tags: true
            all_branches: true
      - stage: release-npm
        name: "Release to NPM"
        script: skip
        deploy:
          provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
          edge: true
          on:
            tags: true
            all_branches: true
notifications:
  email: true
